GET {{api-url}}194620/records/
X-Token: {{token}}

###

GET {{api-url}}youren.ru/records/
X-Token: {{token}}

###

# Устанавливает TXT запись
POST {{api-url}}194620/records/
Content-Type: application/json
X-Token: {{token}}

{
  "name": "@",
  "type": "TXT",
  "content": "tt1=322"
}

####

# Устанавливает CNAME запись
POST {{api-url}}194620/records/
Content-Type: application/json
X-Token: {{token}}

{
  "name": "test2.youren.ru",
  "type": "A",
  "content": "80.87.198.52",
  "ttl": 3000
}

###


# Устанавливает CNAME запись
PUT {{api-url}}194620/records/1816741
Content-Type: application/json
X-Token: {{token}}

{
  "name": "test.youren.ru",
  "type": "TXT",
  "content": "test=3"
}

###

#
PATCH {{api-url}}youren.ru/records/batch_update
Content-Type: application/json
X-Token: {{token}}

{
  "update": [
    {
      "name": "test3.youren.ru",
      "type": "CNAME",
      "content": "sysfile.wumvi.com",
      "id": 1808888
    }
  ],
  "create": [
    {
      "name": "@",
      "type": "TXT",
      "content": "has=1"
    }
  ],
  "delete": [
    {
      "id": 1816729
    }
  ]
}

###
